# Generated by Django 3.1.3 on 2020-11-16 10:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_ending', models.DateField()),
                ('reference', models.CharField(max_length=500)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('topic', models.TextField()),
                ('objectives', models.TextField()),
                ('teacher_learner_activities', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('teaching_learning_materials', models.TextField()),
                ('corepoints', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('evaluation_and_remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'db_table': 'LessonNotes',
            },
        ),
        migrations.AddField(
            model_name='circuitsupervisor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circuitsupervisor',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeeklyLessonNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('daily_notes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lessonnote')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'db_table': 'WeeklyLessonNotes',
            },
        ),
    ]
