# Generated by Django 3.1.3 on 2020-11-18 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201118_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnote',
            name='corepoints',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='evaluation_and_remarks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='objectives',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='teacher_learner_activities',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='teaching_learning_materials',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='topic',
            field=models.CharField(max_length=500),
        ),
    ]
